# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
   get_certificates           # invokes cert
  get_provisioning_profile   # invokes sigh
   build_app(
      export_method: "ad-hoc",
     scheme: "nusmedicine",
     workspace: "nusmedicine.xcworkspace",
      include_bitcode: true,
   )
    crashlytics(
       api_token: "0f0084a0d929105cf47a24b38dd81f81901f8898",
      build_secret: "a429bc1d026280dc76172be9fa9b8d4c7afbdf2b261dc836bc1e3b6f8b32c7c3",
      notifications: "true"
    )
  end
end
