# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

generated_fastfile_id "b2c234c3-4ca9-46a2-bdfa-a24a6a3e08b5"

default_platform(:android)

platform :android do
 desc "Submit a new Beta Build to Crashlytics Beta"
 desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
    crashlytics(
      api_token: "0f0084a0d929105cf47a24b38dd81f81901f8898",
      build_secret: "a429bc1d026280dc76172be9fa9b8d4c7afbdf2b261dc836bc1e3b6f8b32c7c3",
      notifications: "true",
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
